"use client";

import { useMemo } from "react";
import { CalendarClock, Wallet, AlertTriangle, Info } from "lucide-react";

import { generateInstallmentSchedule } from "@/lib/subscriberLifecycle";
import { addDays } from "@/lib/subscriberFinance";
import { MAX_INSTALLMENTS } from "@/constants/billing";
import { INSTALLMENT_FREQUENCY_LABELS } from "@/types/billing";
import type { InstallmentFrequency, PaymentPlanType } from "@/types/billing";
import { formatNumber, formatDate } from "@/lib/utils";

export interface PaymentPlanValue {
  type: PaymentPlanType;
  installmentCount: number;
  firstDueDate: string;
  frequency: InstallmentFrequency;
}

export function defaultPaymentPlan(startDate: string): PaymentPlanValue {
  return {
    type: "full",
    installmentCount: 3,
    // A month out, not today: an instalment due the day it is created is
    // already a payment, and the operator meant the *next* one.
    firstDueDate: addDays(startDate || new Date().toISOString().slice(0, 10), 30),
    frequency: "monthly",
  };
}

const ACC = { indigo: "#5B5FEF", amber: "#F59E0B", rose: "#EF4444", emerald: "#22C55E" };

/**
 * How the rest of the price will be collected.
 *
 * The server has accepted a `paymentPlan` since the ledger shipped; nothing in
 * the UI ever sent one, so instalments were an API-only feature. This is the
 * missing control, shared by the create and renewal modals so the two cannot
 * drift into offering different plans.
 *
 * The schedule preview is generated by the same function the server uses, from
 * the same inputs — including the rounding rule that puts the remainder on the
 * final instalment. What the operator reads here is exactly what will be
 * written, down to the cent, rather than an approximation that disagrees with
 * the saved result.
 */
export default function PaymentPlanPicker({
  totalOriginal,
  downPaymentOriginal,
  exchangeRate,
  currency,
  startDate,
  value,
  onChange,
  disabled,
}: {
  totalOriginal: number;
  downPaymentOriginal: number;
  exchangeRate: number;
  currency: string;
  startDate: string;
  value: PaymentPlanValue;
  onChange: (v: PaymentPlanValue) => void;
  disabled?: boolean;
}) {
  const financed = Math.max(0, totalOriginal - downPaymentOriginal);

  const { schedule, error } = useMemo(() => {
    if (value.type !== "installments") return { schedule: [], error: "" };
    try {
      return {
        schedule: generateInstallmentSchedule({
          totalOriginal,
          downPaymentOriginal,
          exchangeRate: exchangeRate > 0 ? exchangeRate : 1,
          count: value.installmentCount,
          firstDueDate: value.firstDueDate || addDays(startDate, 30),
          frequency: value.frequency,
        }),
        error: "",
      };
    } catch (e) {
      return { schedule: [], error: e instanceof Error ? e.message : "تعذّر توليد الجدول" };
    }
  }, [value, totalOriginal, downPaymentOriginal, exchangeRate, startDate]);

  const set = (patch: Partial<PaymentPlanValue>) => onChange({ ...value, ...patch });

  return (
    <div className="rounded-xl p-3 space-y-3" style={{ border: "1px solid var(--border)", background: "var(--surface)" }}>
      <div className="flex items-center gap-2">
        <Wallet size={14} style={{ color: ACC.indigo }} />
        <span className="text-xs font-bold" style={{ color: "var(--text-primary)" }}>خطة السداد</span>
      </div>

      {/* Mode */}
      <div className="grid grid-cols-2 gap-2">
        {([
          { k: "full" as const,         label: "دفعة واحدة",  hint: "المبلغ كامل مستحق الآن" },
          { k: "installments" as const, label: "خطة أقساط",   hint: "المتبقي يُقسَّم على دفعات مؤرَّخة" },
        ]).map((o) => {
          const on = value.type === o.k;
          return (
            <button
              key={o.k}
              type="button"
              disabled={disabled}
              onClick={() => set({ type: o.k })}
              className="px-3 py-2 rounded-xl text-right transition-all disabled:opacity-50"
              style={{
                background: on ? `${ACC.indigo}12` : "var(--surface-2)",
                border: `1px solid ${on ? ACC.indigo : "var(--border)"}`,
                color: on ? ACC.indigo : "var(--text-secondary)",
              }}
            >
              <span className="block text-xs font-bold">{o.label}</span>
              <span className="block text-[10px] opacity-70 mt-0.5">{o.hint}</span>
            </button>
          );
        })}
      </div>

      {value.type === "installments" && (
        <>
          {financed <= 0 ? (
            <p className="flex items-start gap-1.5 text-[11px]" style={{ color: ACC.amber }}>
              <Info size={12} className="shrink-0 mt-0.5" />
              الدفعة المقدَّمة تغطي المبلغ بالكامل — لا يوجد ما يُقسَّط، وستُحفظ كدفعة واحدة.
            </p>
          ) : (
            <>
              <div className="grid grid-cols-3 gap-2">
                <div>
                  <label className="block text-[11px] font-semibold mb-1" style={{ color: "var(--text-secondary)" }}>
                    عدد الأقساط
                  </label>
                  <input
                    type="number" min={1} max={MAX_INSTALLMENTS} disabled={disabled}
                    value={value.installmentCount}
                    onChange={(e) => set({ installmentCount: Math.max(1, parseInt(e.target.value) || 1) })}
                    className="form-input w-full"
                  />
                </div>
                <div>
                  <label className="block text-[11px] font-semibold mb-1" style={{ color: "var(--text-secondary)" }}>
                    التكرار
                  </label>
                  <select
                    disabled={disabled}
                    value={value.frequency}
                    onChange={(e) => set({ frequency: e.target.value as InstallmentFrequency })}
                    className="form-input w-full"
                  >
                    {(["weekly", "biweekly", "monthly"] as const).map((f) => (
                      <option key={f} value={f}>{INSTALLMENT_FREQUENCY_LABELS[f]}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-[11px] font-semibold mb-1" style={{ color: "var(--text-secondary)" }}>
                    أول استحقاق
                  </label>
                  <input
                    type="date" disabled={disabled}
                    value={value.firstDueDate}
                    onChange={(e) => set({ firstDueDate: e.target.value })}
                    className="form-input w-full"
                  />
                </div>
              </div>

              {error ? (
                <p className="flex items-start gap-1.5 text-[11px]" style={{ color: ACC.rose }}>
                  <AlertTriangle size={12} className="shrink-0 mt-0.5" />
                  {error}
                </p>
              ) : (
                <div className="rounded-lg overflow-hidden" style={{ border: "1px solid var(--border)" }}>
                  <div
                    className="flex items-center justify-between px-3 py-1.5 text-[11px] font-bold"
                    style={{ background: "var(--surface-2)", color: "var(--text-secondary)" }}
                  >
                    <span className="flex items-center gap-1.5">
                      <CalendarClock size={11} /> جدول الأقساط
                    </span>
                    <span className="tabular-nums">
                      {formatNumber(financed, 2)} {currency}
                      {exchangeRate > 0 && currency !== "USD" && (
                        <span className="opacity-60"> ≈ ${formatNumber(financed / exchangeRate, 2)}</span>
                      )}
                    </span>
                  </div>
                  <div className="max-h-40 overflow-y-auto">
                    {schedule.map((s) => (
                      <div
                        key={s.installmentNumber}
                        className="flex items-center justify-between px-3 py-1.5 text-[11px] border-b last:border-0"
                        style={{ borderColor: "var(--divider)", color: "var(--text-secondary)" }}
                      >
                        <span>قسط #{s.installmentNumber}</span>
                        <span>{formatDate(s.dueDate)}</span>
                        <span className="tabular-nums font-bold" style={{ color: "var(--text-primary)" }}>
                          {formatNumber(s.amountOriginal, 2)} {currency}
                        </span>
                      </div>
                    ))}
                  </div>
                  {/*
                    Stated explicitly because the last instalment differs: the
                    rounding remainder lands there so the schedule sums back to
                    the financed amount exactly, and an operator who spots the
                    odd cent should know it is deliberate.
                  */}
                  {schedule.length > 1 &&
                    Math.abs(schedule[schedule.length - 1].amountOriginal - schedule[0].amountOriginal) > 0.001 && (
                    <p className="px-3 py-1.5 text-[10px]" style={{ color: "var(--text-muted)", background: "var(--surface-2)" }}>
                      القسط الأخير يحمل فرق التقريب حتى يطابق المجموع المبلغ المتبقي تماماً.
                    </p>
                  )}
                </div>
              )}
            </>
          )}
        </>
      )}

      {value.type === "full" && downPaymentOriginal > 0 && downPaymentOriginal < totalOriginal && (
        <p className="flex items-start gap-1.5 text-[11px]" style={{ color: ACC.amber }}>
          <Info size={12} className="shrink-0 mt-0.5" />
          سيبقى <b>{formatNumber(financed, 2)} {currency}</b> مستحقاً بلا تاريخ محدَّد. اختر «خطة أقساط»
          إذا أردت جدولة المتبقي.
        </p>
      )}
    </div>
  );
}

/** The payload shape /api/subscriber-operations expects, or undefined for full. */
export function toPaymentPlanPayload(v: PaymentPlanValue, financedOriginal: number) {
  if (v.type !== "installments" || financedOriginal <= 0) return undefined;
  return {
    type: "installments" as const,
    installmentCount: v.installmentCount,
    firstDueDate: v.firstDueDate,
    frequency: v.frequency,
  };
}
